#############################################################################
# Makefile for building: FonteLed4K
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  FonteLed4K.pro
# Template: app
# Command: /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/qmake -o Makefile FonteLed4K.pro -spec linux-oe-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-guf-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi
CXX           = arm-guf-linux-gnueabi-g++  -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe  -O2 -pipe -g -feliminate-unused-debug-types  --sysroot=/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi -O2 -DLINUX=1 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe  -O2 -pipe -g -feliminate-unused-debug-types  --sysroot=/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi -O2 -DLINUX=1 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5 -isystem /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuickControls2 -isystem /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuick -isystem /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtGui -isystem /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQml -isystem /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtNetwork -isystem /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtSerialPort -isystem /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtCore -I. -I/home/jenkins/workspace/Yocto-Rocko/build-image/build-imx6guf/tmp/work/cortexa9hf-neon-mx6qdl-guf-linux-gnueabi/qtbase/5.9.4+gitAUTOINC+0d9208cecb-r0/recipe-sysroot/usr/include/libdrm -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++
QMAKE         = /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/qmake -install qinstall
QINSTALL_PROGRAM = /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = FonteLed4K1.0.0
DISTDIR = /home/astus/Imagens/FonteLed4K_25_05_18/.tmp/FonteLed4K1.0.0
LINK          = arm-guf-linux-gnueabi-g++  -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi
LFLAGS        = -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed --sysroot=/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi -Wl,-O1 -Wl,-rpath-link,/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib
LIBS          = $(SUBLIBS) -lQt5QuickControls2 -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5SerialPort -lQt5Core -lGLESv2 -lEGL -lpthread 
AR            = arm-guf-linux-gnueabi-ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		serialike.cpp \
		gpio.cpp \
		senha.cpp \
		calendario.cpp \
		init.cpp qrc_qml.cpp \
		qrc_resources.cpp \
		moc_serialike.cpp \
		moc_gpio.cpp \
		moc_senha.cpp \
		moc_calendario.cpp \
		moc_init.cpp
OBJECTS       = main.o \
		serialike.o \
		gpio.o \
		senha.o \
		calendario.o \
		init.o \
		qrc_qml.o \
		qrc_resources.o \
		moc_serialike.o \
		moc_gpio.o \
		moc_senha.o \
		moc_calendario.o \
		moc_init.o
DIST          = /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/qdevice.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/device_config.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf \
		FonteLed4K.pro serialike.h \
		gpio.h \
		senha.h \
		calendario.h \
		init.h main.cpp \
		serialike.cpp \
		gpio.cpp \
		senha.cpp \
		calendario.cpp \
		init.cpp
QMAKE_TARGET  = FonteLed4K
DESTDIR       = 
TARGET        = FonteLed4K


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FonteLed4K.pro /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/qdevice.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/device_config.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf \
		FonteLed4K.pro \
		qml.qrc \
		resources.qrc \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5QuickControls2.prl \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5Quick.prl \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5Gui.prl \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5Qml.prl \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5Network.prl \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5SerialPort.prl \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile FonteLed4K.pro -spec linux-oe-g++
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/qdevice.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/device_config.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_charts.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/toolchain.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf:
FonteLed4K.pro:
qml.qrc:
resources.qrc:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5QuickControls2.prl:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5Quick.prl:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5Gui.prl:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5Qml.prl:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5Network.prl:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5SerialPort.prl:
/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile FonteLed4K.pro -spec linux-oe-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents serialike.h gpio.h senha.h calendario.h init.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp serialike.cpp gpio.cpp senha.cpp calendario.cpp init.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp qrc_resources.cpp
qrc_qml.cpp: qml.qrc \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/rcc \
		EditHours.qml \
		Menu.qml \
		Calendario.qml \
		SerialNumber.qml \
		Senha.qml \
		Brilho.qml \
		Inicializacao.qml \
		Configuration.qml \
		main.qml \
		TelaLed.qml \
		ResetHoras.png
	/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/rcc -name qml qml.qrc -o qrc_qml.cpp

qrc_resources.cpp: resources.qrc \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/rcc \
		imagesInit/loading_5.bmp \
		imagesInit/loading_9.bmp \
		imagesInit/loading_0.bmp \
		imagesInit/loading_4.bmp \
		imagesInit/loading_10.bmp \
		imagesInit/loading_8.bmp \
		imagesInit/loading_3.bmp \
		imagesInit/loading_7.bmp \
		imagesInit/connectOn.png \
		imagesInit/loading_2.bmp \
		imagesInit/connectOff.png \
		imagesInit/loading_6.bmp \
		imagesInit/telaInit.bmp \
		imagesInit/loading_1.bmp \
		IconesBrilho/Barra70.jpg \
		IconesBrilho/Minus.jpg \
		IconesBrilho/Barra00.jpg \
		IconesBrilho/Barra30.jpg \
		IconesBrilho/Barra60.jpg \
		IconesBrilho/Barra90.jpg \
		IconesBrilho/Barra100.jpg \
		IconesBrilho/Barra20.jpg \
		IconesBrilho/Barra50.jpg \
		IconesBrilho/Barra80.jpg \
		IconesBrilho/Barra10.jpg \
		IconesBrilho/Back.jpg \
		IconesBrilho/IconeBrilho.jpg \
		IconesBrilho/Mais.jpg \
		IconesBrilho/Barra40.jpg \
		IconesLed/Plus.bmp \
		IconesLed/Minus.bmp \
		Telas/calendario.bmp \
		Telas/19_principal.bmp \
		Telas/telaUser.png \
		Telas/Menu.bmp \
		Telas/MediaStateFailure.bmp \
		Telas/telaPrincipalCamera.bmp \
		Telas/TelaCal.png \
		Telas/brilho_.jpg \
		Telas/SerialNumber.bmp \
		Telas/NoMedia.bmp \
		Telas/editHoras.bmp \
		Telas/TelaConfig.bmp \
		Telas/MidiaFormat.bmp \
		Telas/senha.bmp \
		../../Documentos/ProjetosQt/FonteLed4K01_03_2019/Telas/editHoras.bmp \
		IndicadoresCentrais/Laparo01.png \
		IndicadoresCentrais/Histero.png \
		IndicadoresCentrais/indi50.png \
		IndicadoresCentrais/indi80.png \
		IndicadoresCentrais/indi10.png \
		IndicadoresCentrais/Endoflexivel.png \
		IndicadoresCentrais/indi40.png \
		IndicadoresCentrais/StandByBranco.png \
		IndicadoresCentrais/indi70.png \
		IndicadoresCentrais/indi00.png \
		IndicadoresCentrais/indi100.png \
		IndicadoresCentrais/indi30.png \
		IndicadoresCentrais/indi60.png \
		IndicadoresCentrais/StandByVerde.png \
		IndicadoresCentrais/Laparo.png \
		IndicadoresCentrais/indi90.png \
		IndicadoresCentrais/indi20.png \
		IconesConfig/ResetHoras.png \
		IconesConfig/BotaoPlus.png \
		IconesConfig/SetaDir.bmp \
		IconesConfig/serialNumber.png \
		IconesConfig/midiaFormat.png \
		IconesConfig/waitt.bmp \
		IconesConfig/setaEsc.bmp \
		IconesConfig/Ok.bmp \
		IconesConfig/Esc3cmos.bmp \
		IconesConfig/Esc1cmos.bmp \
		IconesConfig/configuration.png \
		IconesConfig/Preset.bmp \
		IconesConfig/Hysteroparam.bmp \
		IconesConfig/negado.bmp \
		IconesConfig/inicio.bmp \
		IconesConfig/si.png \
		IconesConfig/SetaDown.bmp \
		IconesConfig/nada.bmp \
		IconesConfig/Endoparam.bmp \
		IconesConfig/cancel.bmp \
		IconesConfig/formatmidiayes.png \
		IconesConfig/SetaOk.bmp \
		IconesConfig/LaP01Param.bmp \
		IconesConfig/edithourLamp.bmp \
		IconesConfig/formatmidianNot.png \
		IconesConfig/SetaUp.bmp \
		IconesConfig/Calendario.png \
		IconesConfig/BotaoMinus.png \
		IconesConfig/LaP02Param.bmp \
		IconesSenha/8.bmp \
		IconesSenha/asterisco0.bmp \
		IconesSenha/del.bmp \
		IconesSenha/asterisco4.bmp \
		IconesSenha/3.bmp \
		IconesSenha/enter.bmp \
		IconesSenha/7.bmp \
		IconesSenha/asterisco3.bmp \
		IconesSenha/2.bmp \
		IconesSenha/6.bmp \
		IconesSenha/asterisco2.bmp \
		IconesSenha/1.bmp \
		IconesSenha/5.bmp \
		IconesSenha/9.bmp \
		IconesSenha/asterisco1.bmp \
		IconesSenha/0.bmp \
		IconesSenha/4.bmp \
		IconesCalUsers/Esclp3.bmp \
		IconesCalUsers/Laparo02.bmp \
		IconesCalUsers/Printlp3.bmp \
		IconesCalUsers/Esclp2.bmp \
		IconesCalUsers/Laparo01.bmp \
		IconesCalUsers/Printlp2.bmp \
		IconesCalUsers/Esclp1.bmp \
		IconesCalUsers/Printlp1.bmp \
		IconesCalUsers/Esclp0.bmp \
		IconesCalUsers/Esclp4.bmp \
		IconesCalUsers/Endoflexible.bmp \
		IconesCalUsers/HysteroUro.bmp \
		IconesCalUsers/Printlp4.bmp \
		Icones/Laparo01.png \
		Icones/EnhanceOff.png \
		Icones/BotaoMenu.png \
		Icones/wbNegado.bmp \
		Icones/Userlaparo2.png \
		Icones/HomeBack.png \
		Icones/Enhancehigh.png \
		Icones/RecStop.png \
		Icones/Userlaparo1.png \
		Icones/Zoom3.png \
		Icones/UserEndiflexivel.png \
		Icones/Aguarde.png \
		Icones/Zoom2.png \
		Icones/Lamp.png \
		Icones/wbOk.bmp \
		Icones/Endiflexivel.png \
		Icones/Enhancemed.png \
		Icones/RecIni.png \
		Icones/Zoom1.png \
		Icones/SemMedia.png \
		Icones/Nomedia.png \
		Icones/Ganho2.png \
		Icones/Zoom0.png \
		Icones/LAMP.bmp \
		Icones/HistreoUro.png \
		Icones/RecRun.png \
		Icones/Ganho1.png \
		Icones/white2.png \
		Icones/RecReini.png \
		Icones/NoRec.png \
		Icones/Back.png \
		Icones/Ganho0.png \
		Icones/wbShow.bmp \
		Icones/UserHisteroUro.png \
		Icones/white1.png \
		Icones/EnhanceLow.png \
		Icones/Laparo02.png \
		Icones/white0.png
	/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/data/dummy.cpp
	arm-guf-linux-gnueabi-g++  -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi -pipe  -O2 -pipe -g -feliminate-unused-debug-types  --sysroot=/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi -O2 -DLINUX=1 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_serialike.cpp moc_gpio.cpp moc_senha.cpp moc_calendario.cpp moc_init.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_serialike.cpp moc_gpio.cpp moc_senha.cpp moc_calendario.cpp moc_init.cpp
moc_serialike.cpp: serialike.h \
		moc_predefs.h \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/moc
	/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/moc $(DEFINES) --include ./moc_predefs.h -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/astus/Imagens/FonteLed4K_25_05_18 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuickControls2 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuick -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtGui -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQml -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtNetwork -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtSerialPort -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtCore -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0/arm-guf-linux-gnueabi -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0/backward -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/lib/arm-guf-linux-gnueabi/gcc/arm-guf-linux-gnueabi/7.3.0/include -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/gcc/arm-guf-linux-gnueabi/7.3.0/include -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/lib/arm-guf-linux-gnueabi/gcc/arm-guf-linux-gnueabi/7.3.0/include-fixed -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include serialike.h -o moc_serialike.cpp

moc_gpio.cpp: serialike.h \
		gpio.h \
		moc_predefs.h \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/moc
	/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/moc $(DEFINES) --include ./moc_predefs.h -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/astus/Imagens/FonteLed4K_25_05_18 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuickControls2 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuick -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtGui -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQml -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtNetwork -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtSerialPort -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtCore -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0/arm-guf-linux-gnueabi -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0/backward -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/lib/arm-guf-linux-gnueabi/gcc/arm-guf-linux-gnueabi/7.3.0/include -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/gcc/arm-guf-linux-gnueabi/7.3.0/include -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/lib/arm-guf-linux-gnueabi/gcc/arm-guf-linux-gnueabi/7.3.0/include-fixed -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include gpio.h -o moc_gpio.cpp

moc_senha.cpp: senha.h \
		moc_predefs.h \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/moc
	/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/moc $(DEFINES) --include ./moc_predefs.h -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/astus/Imagens/FonteLed4K_25_05_18 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuickControls2 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuick -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtGui -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQml -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtNetwork -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtSerialPort -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtCore -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0/arm-guf-linux-gnueabi -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0/backward -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/lib/arm-guf-linux-gnueabi/gcc/arm-guf-linux-gnueabi/7.3.0/include -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/gcc/arm-guf-linux-gnueabi/7.3.0/include -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/lib/arm-guf-linux-gnueabi/gcc/arm-guf-linux-gnueabi/7.3.0/include-fixed -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include senha.h -o moc_senha.cpp

moc_calendario.cpp: calendario.h \
		moc_predefs.h \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/moc
	/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/moc $(DEFINES) --include ./moc_predefs.h -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/astus/Imagens/FonteLed4K_25_05_18 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuickControls2 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuick -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtGui -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQml -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtNetwork -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtSerialPort -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtCore -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0/arm-guf-linux-gnueabi -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0/backward -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/lib/arm-guf-linux-gnueabi/gcc/arm-guf-linux-gnueabi/7.3.0/include -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/gcc/arm-guf-linux-gnueabi/7.3.0/include -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/lib/arm-guf-linux-gnueabi/gcc/arm-guf-linux-gnueabi/7.3.0/include-fixed -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include calendario.h -o moc_calendario.cpp

moc_init.cpp: init.h \
		moc_predefs.h \
		/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/moc
	/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/bin/qt5/moc $(DEFINES) --include ./moc_predefs.h -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/astus/Imagens/FonteLed4K_25_05_18 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuickControls2 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQuick -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtGui -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtQml -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtNetwork -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtSerialPort -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/qt5/QtCore -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0 -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0/arm-guf-linux-gnueabi -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include/c++/7.3.0/backward -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/lib/arm-guf-linux-gnueabi/gcc/arm-guf-linux-gnueabi/7.3.0/include -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/lib/gcc/arm-guf-linux-gnueabi/7.3.0/include -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/x86_64-gufsdk-linux/usr/lib/arm-guf-linux-gnueabi/gcc/arm-guf-linux-gnueabi/7.3.0/include-fixed -I/opt/guf/GUF-Yocto-rocko-1.0-0-sdk/sysroots/imx6guf-guf-linux-gnueabi/usr/include init.h -o moc_init.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp serialike.h \
		gpio.h \
		senha.h \
		calendario.h \
		init.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

serialike.o: serialike.cpp serialike.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialike.o serialike.cpp

gpio.o: gpio.cpp gpio.h \
		serialike.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpio.o gpio.cpp

senha.o: senha.cpp senha.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o senha.o senha.cpp

calendario.o: calendario.cpp calendario.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calendario.o calendario.cpp

init.o: init.cpp init.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o init.o init.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_serialike.o: moc_serialike.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialike.o moc_serialike.cpp

moc_gpio.o: moc_gpio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gpio.o moc_gpio.cpp

moc_senha.o: moc_senha.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_senha.o moc_senha.cpp

moc_calendario.o: moc_calendario.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calendario.o moc_calendario.cpp

moc_init.o: moc_init.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_init.o moc_init.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/FonteLed4K/bin || mkdir -p $(INSTALL_ROOT)/opt/FonteLed4K/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/FonteLed4K/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/FonteLed4K/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/FonteLed4K/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

